-- Oracle DDL for master schema
-- Note: remove IF NOT EXISTS (not supported). Use identity column for id and NUMBER(1) for boolean.

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE tenants';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF; -- ignore table does not exist
END;
/

CREATE TABLE tenants (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR2(64) UNIQUE NOT NULL,
  db_url VARCHAR2(512),
  db_username VARCHAR2(150),
  db_password VARCHAR2(150),
  driver_class VARCHAR2(200),
  jndi_name VARCHAR2(255),
  active NUMBER(1) DEFAULT 1 NOT NULL
);

INSERT INTO tenants (tenant_id, db_url, db_username, db_password, driver_class, active) VALUES
('tenant1', 'jdbc:oracle:thin:@//localhost:1521/DATASTORE', 'TENANT2', 'TENANT2', 'oracle.jdbc.OracleDriver', 1);

INSERT INTO tenants (tenant_id, db_url, db_username, db_password, driver_class, active) VALUES
('tenant2', 'jdbc:oracle:thin:@//localhost:1521/DATASTORE', 'TENANT2', 'TENANT2', 'oracle.jdbc.OracleDriver', 1);

COMMIT;
