DECLARE
    v_count INTEGER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'TEAMS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE teams (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(200) NOT NULL,
                city VARCHAR2(200)
            )';
    END IF;
END;
/

DECLARE
    v_count INTEGER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'PLAYERS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE players (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                full_name VARCHAR2(200) NOT NULL,
                role VARCHAR2(50),
                team_id NUMBER,
                CONSTRAINT fk_players_team FOREIGN KEY (team_id) REFERENCES teams(id)
            )';
    END IF;
END;
/

DECLARE
    v_count INTEGER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'TOURNAMENTS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE tournaments (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(200) NOT NULL,
                year NUMBER(4) NOT NULL
            )';
    END IF;
END;
/

DECLARE
    v_count INTEGER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'MATCHES';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE matches (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tournament_id NUMBER,
                home_team_id NUMBER,
                away_team_id NUMBER,
                match_date DATE,
                venue VARCHAR2(200),
                home_score NUMBER,
                away_score NUMBER,
                CONSTRAINT fk_matches_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
                CONSTRAINT fk_matches_home_team FOREIGN KEY (home_team_id) REFERENCES teams(id),
                CONSTRAINT fk_matches_away_team FOREIGN KEY (away_team_id) REFERENCES teams(id)
            )';
    END IF;
END;
/