server:
  port: 8080

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

multitenant:
  header: X-Tenant-Id
  # Oracle master DB connection (choose either direct JDBC or JNDI)
  # master-jdbc-url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
  # master-username: MASTER_USER
  # master-password: MASTER_PASS
  # or master-jndi: java:comp/env/jdbc/master
